import { useState } from 'react';
import type { KnowledgeSearchResponse } from '../../domain/entities/knowledge';

export function KnowledgeSearchPanel({ semanticReady, result, onSearch }: { semanticReady: boolean; result: KnowledgeSearchResponse | null; onSearch: (query: string) => void }) {
  const [query, setQuery] = useState('');
  return <section className="rounded-2xl border border-outline-variant bg-surface-container-lowest p-5 shadow-sm sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-ui-label-caps text-ui-label-caps uppercase tracking-wider text-secondary">Retrieval console</p><h3 className="mt-1 font-display-serif text-[25px] text-primary">Tìm bằng câu hỏi thật</h3></div><span className={`rounded-full px-2.5 py-1 font-ui-label-bold text-[11px] ${semanticReady ? 'bg-[#e2f3e6] text-[#216a38]' : 'bg-surface-container text-on-surface-variant'}`}>{semanticReady ? 'Semantic ready' : 'Lexical fallback'}</span></div>
    <div className="mt-5 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') onSearch(query); }} className="min-w-0 flex-1 rounded-xl border border-outline-variant bg-surface px-4 py-3 text-[14px] outline-none transition focus:border-secondary focus:ring-2 focus:ring-secondary/10" placeholder="Ví dụ: Chính sách hoàn tiền quy định thế nào?" /><button onClick={() => onSearch(query)} disabled={!query.trim()} className="rounded-xl bg-secondary px-4 text-on-secondary transition hover:bg-on-secondary-container disabled:cursor-not-allowed disabled:opacity-40" title="Tìm trong tri thức"><span className="material-symbols-outlined text-[20px]">search</span></button></div>
    {result && <SearchResults result={result} />}
  </section>;
}

function SearchResults({ result }: { result: KnowledgeSearchResponse }) {
  return <div className="mt-6 border-t border-outline-variant pt-5"><div className="mb-4 flex items-center justify-between"><p className="font-ui-label-bold text-[13px] text-primary">{result.results.length} đoạn liên quan</p><span className="font-code-base text-[11px] text-on-surface-variant">{result.mode === 'hybrid' ? 'RRF + MMR' : 'BM25 + MMR'}</span></div><div className="space-y-3">{result.results.map((item, index) => <article key={item.chunkId} className="rounded-xl border border-outline-variant bg-surface p-4 transition hover:border-secondary/60"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-ui-label-bold text-[13px] text-primary">{item.sourceName}</p><p className="mt-0.5 truncate font-code-base text-[11px] text-secondary">{item.section}</p></div><span className="shrink-0 font-code-base text-[11px] text-on-surface-variant">#{index + 1}</span></div><p className="mt-3 whitespace-pre-line text-[13px] leading-5 text-on-surface-variant">{item.excerpt}</p><div className="mt-3 flex items-center justify-between border-t border-outline-variant/60 pt-2 text-[10px] font-code-base text-on-surface-variant"><span>{item.citation}</span><span>{result.mode === 'hybrid' ? `S ${item.semanticScore.toFixed(2)}` : `L ${item.lexicalScore.toFixed(2)}`}</span></div></article>)}{result.results.length === 0 && <p className="rounded-lg bg-surface-container px-4 py-3 text-[13px] text-on-surface-variant">Không tìm thấy đoạn đủ liên quan. Hãy thử dùng từ khóa cụ thể hơn hoặc thêm tài liệu.</p>}</div></div>;
}
