import type { AgentToolDefinition } from '../../domain/entities/tool.js';

export const LOCAL_TOOL_DEFINITIONS: AgentToolDefinition[] = [
  { name: 'list_files', description: 'List files and folders inside the current workspace.', risk: 'read', concurrencySafe: true, parameters: { properties: { dir: { type: 'string', description: 'Workspace-relative directory. Defaults to current workspace root.' }, maxEntries: { type: 'number', description: 'Maximum entries to return.' } } } },
  { name: 'read_file', description: 'Read UTF-8 text, images, PDFs, or Jupyter notebooks. Images are shown visually; PDFs over 10 pages require a pages range of at most 20 pages.', risk: 'read', concurrencySafe: true, parameters: { additionalProperties: false, properties: { path: { type: 'string', description: 'Workspace-relative file path.' }, offset: { type: 'integer', minimum: 1 }, limit: { type: 'integer', minimum: 1, maximum: 10_000 }, pages: { type: 'string', description: 'PDF page or inclusive range, for example 3 or 1-5.' } }, required: ['path'] } },
  { name: 'glob', description: 'Find files recursively by a workspace-relative glob pattern.', risk: 'read', concurrencySafe: true, parameters: { properties: { pattern: { type: 'string', description: 'Relative glob such as **/*.ts.' }, path: { type: 'string', description: 'Optional workspace-relative search root.' }, maxResults: { type: 'integer', description: 'Maximum matching paths to return.' } }, required: ['pattern'] } },
  { name: 'grep', description: 'Search text files recursively and return path:line evidence. Literal by default; set regex=true for a guarded regular expression.', risk: 'read', concurrencySafe: true, parameters: { properties: { pattern: { type: 'string', description: 'Text or guarded regular expression.' }, path: { type: 'string', description: 'Optional workspace-relative search root.' }, glob: { type: 'string', description: 'Optional relative file filter such as **/*.ts.' }, regex: { type: 'boolean' }, caseSensitive: { type: 'boolean' }, maxResults: { type: 'integer' } }, required: ['pattern'] } },
  { name: 'write_file', description: 'Write complete UTF-8 content to a workspace file.', risk: 'write', parameters: { properties: { path: { type: 'string', description: 'Workspace-relative file path.' }, content: { type: 'string', description: 'Full file content.' } }, required: ['path', 'content'] } },
  { name: 'apply_patch', description: 'Replace one exact text block in an existing UTF-8 file without resending the entire file.', risk: 'write', parameters: { properties: { path: { type: 'string', description: 'Workspace-relative file path.' }, oldText: { type: 'string', description: 'Exact existing text to replace. It must occur exactly once.' }, newText: { type: 'string', description: 'Replacement text.' } }, required: ['path', 'oldText', 'newText'] } },
  { name: 'run_command', description: 'Run a shell command in the workspace.', risk: 'execute', parameters: { properties: { command: { type: 'string', description: 'Shell command to run.' }, timeoutMs: { type: 'number', description: 'Timeout in milliseconds, max 600000.' } }, required: ['command'] } },
  { name: 'web_search', description: 'Search the public web through the configured connector.', risk: 'network', deferLoading: true, searchHint: 'search public web internet', parameters: { properties: { query: { type: 'string', description: 'Focused web search query.' }, domains: { type: 'string', description: 'Optional comma-separated domains.' } }, required: ['query'] } },
  { name: 'load_skill', description: 'Load the full instructions for a user-trusted and enabled Agent Skill by id.', risk: 'read', concurrencySafe: true, parameters: { properties: { skillId: { type: 'string', description: 'Skill id listed in the system prompt.' }, args: { type: 'string', description: 'Optional arguments for this invocation.' } }, required: ['skillId'] } },
];

export function getLocalToolDefinition(toolName: string) {
  return LOCAL_TOOL_DEFINITIONS.find((tool) => tool.name === toolName);
}
