import type { NodeCheckpoint, WorkflowDefinition } from '../domain/entities/workflow';
import { useWorkflows } from '../application/hooks/useWorkflows';

export function WorkflowView() {
  const { definitions, runs, notice, busy, refresh, start, decide } = useWorkflows();
  return <div className="flex-1 overflow-y-auto px-6 py-8"><div className="max-w-[1050px] mx-auto"><header className="flex justify-between border-b border-outline-variant pb-5 mb-6"><div><p className="text-ui-label-caps uppercase text-secondary">Deterministic graph runtime</p><h2 className="font-display-serif text-[30px] text-primary">Workflows</h2><p className="text-[13px] text-on-surface-variant">Sequence, branch, bounded retry, durable approval and parallel read-only nodes.</p></div><button onClick={() => void refresh()} className="settings-action">Làm mới</button></header>
    <section className="grid grid-cols-2 gap-4 mb-8">{definitions.map((definition) => <DefinitionCard key={definition.id} definition={definition} disabled={busy} onStart={() => void start(definition.id)} />)}</section>
    <h3 className="font-ui-label-bold text-[15px] mb-3">Workflow runs</h3><div className="space-y-3">{runs.map((run) => <RunCard key={run.runId} run={run} definition={definitions.find((item) => item.id === run.workflowId)} onDecision={(approved) => void decide(run, approved)} />)}{runs.length === 0 && <p className="text-[13px] text-on-surface-variant">Chưa có workflow run.</p>}</div>{notice && <p className="text-[13px] text-secondary mt-4">{notice}</p>}
  </div></div>;
}

function DefinitionCard({ definition, disabled, onStart }: { definition: WorkflowDefinition; disabled: boolean; onStart: () => void }) { const kinds = [...new Set(definition.nodes.map((node) => node.kind))]; return <article className="border border-outline-variant rounded-xl bg-surface-container-lowest p-5"><div className="flex justify-between"><div><h3 className="font-semibold">{definition.name}</h3><p className="text-[11px] text-on-surface-variant">{definition.id}@{definition.version}</p></div><button disabled={disabled} onClick={onStart} className="px-3 py-1.5 rounded bg-primary text-on-primary text-[12px]">Chạy</button></div><div className="flex gap-1 mt-4">{kinds.map((kind) => <span key={kind} className="text-[9px] uppercase bg-surface-container rounded px-2 py-1">{kind}</span>)}</div></article>; }
function RunCard({ run, definition, onDecision }: { run: NodeCheckpoint; definition?: WorkflowDefinition; onDecision: (approved: boolean) => void }) { const awaiting = run.status === 'paused' && definition?.nodes.find((node) => node.id === run.currentNodeId)?.kind === 'approval'; return <article className="border border-outline-variant rounded-xl bg-surface-container-lowest p-4"><div className="flex justify-between gap-3"><div><span className={`${run.status === 'completed' ? 'bg-[#2e7d32]' : run.status === 'failed' ? 'bg-error' : 'bg-secondary'} text-white text-[10px] uppercase rounded px-2 py-0.5`}>{run.status}</span><span className="ml-2 font-semibold text-[13px]">{definition?.name || run.workflowId}</span><p className="font-code-base text-[10px] text-on-surface-variant mt-2">{run.runId} · {run.executions.length} executions</p></div>{awaiting && <div className="flex gap-2"><button onClick={() => onDecision(false)} className="settings-action text-error">Từ chối</button><button onClick={() => onDecision(true)} className="px-3 py-1 rounded bg-primary text-on-primary text-[12px]">Phê duyệt</button></div>}</div><div className="flex flex-wrap gap-1 mt-3">{run.executions.map((execution) => <span key={execution.nodeId} className="text-[10px] border border-outline-variant rounded px-2 py-1">{execution.nodeId}: {execution.status} ({execution.attempts})</span>)}</div></article>; }
